export const USER_REPOSITORY = 'USER_REPOSITORY'
export const ROLE_REPOSITORY = 'ROLE_REPOSITORY'
export const USER_ROLE_REPOSITORY = 'USER_ROLE_REPOSITORY'
export const EMAIL_VERIFICATION_CODE_REPOSITORY = 'EMAIL_VERIFICATION_CODE_REPOSITORY'
