services:
  user-service:
    container_name: user-service
    build: .
    ports:
      - 3001:3001
    env_file:
      - .env
    command: ['./command.sh']
    depends_on:
      - db-user-service
    networks:
      - task-manager-network

  db-user-service:
    container_name: db-user-service
    image: postgres:17
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db-user-service
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - task-manager-network

networks:
  task-manager-network:
    external: true

volumes:
  db-data:

